# Generated by Django 3.2.3 on 2021-06-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.categories'),
            preserve_default=False,
        ),
    ]
