# Generated by Django 3.2.3 on 2021-06-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_info_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='info_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
