# Generated by Django 3.2.3 on 2021-06-23 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_info_info_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.info')),
            ],
        ),
    ]
