# Generated by Django 3.2.3 on 2021-06-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_info1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info1',
            name='info',
        ),
        migrations.RemoveField(
            model_name='info',
            name='category',
        ),
        migrations.AddField(
            model_name='info',
            name='tag',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Info1',
        ),
    ]
