# Generated by Django 3.2.3 on 2021-06-24 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_info_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='tag',
        ),
        migrations.AddField(
            model_name='info',
            name='tag_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.tags'),
            preserve_default=False,
        ),
    ]
