# Generated by Django 3.2.3 on 2021-06-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210624_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='tag',
        ),
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
