# Generated by Django 3.2.3 on 2021-06-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210626_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
