# Generated by Django 3.2.3 on 2021-06-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0011_delete_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=3000)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
