# Generated by Django 3.2.3 on 2021-06-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='tags',
            field=models.ManyToManyField(to='news.Tag'),
        ),
    ]
