# Generated by Django 3.2.3 on 2021-06-29 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20210629_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='tags',
        ),
        migrations.AddField(
            model_name='info',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.tag'),
            preserve_default=False,
        ),
    ]
