# Generated by Django 3.2.3 on 2021-06-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20210629_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='tags',
        ),
        migrations.AddField(
            model_name='info',
            name='tag',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
