# Generated by Django 3.2.3 on 2021-07-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20210629_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='tag',
        ),
        migrations.AlterField(
            model_name='info',
            name='info',
            field=models.TextField(),
        ),
    ]
