# Generated by Django 3.2.3 on 2021-07-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20210729_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
