# Generated by Django 3.2.7 on 2022-01-16 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='cat_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.category'),
            preserve_default=False,
        ),
    ]
